// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/auth/github/callback.ts";
import * as $2 from "./routes/api/auth/github/client.ts";
import * as $3 from "./routes/api/auth/github/index.ts";
import * as $4 from "./routes/api/auth/github/webhook.ts";
import * as $5 from "./routes/api/index.ts";
import * as $6 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/auth/github/callback.ts": $1,
    "./routes/api/auth/github/client.ts": $2,
    "./routes/api/auth/github/index.ts": $3,
    "./routes/api/auth/github/webhook.ts": $4,
    "./routes/api/index.ts": $5,
    "./routes/index.tsx": $6,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
